#!/bin/bash

# A hook called when the image is booting, before a user can assume control.

readonly BASE_DIR='/opt/qfcc'
readonly DATA_DIR="${BASE_DIR}/data"
readonly SHORTCUTS_DIR="${DATA_DIR}/shortcuts"
readonly FORCE_REMOVE_PACKAGES_PATH="${DATA_DIR}/remove-force.txt"

function setup_users() {
    echo "Setting Up Users"

    echo 'qfcc:qfcc' | chpasswd
}

function setup_desktop() {
    echo "Setting up Desktop"

    chown -R qfcc:qfcc /home/qfcc/Desktop
    echo 'XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share:/home/qfcc/Desktop' >> /etc/environment
}

function remove_files() {
    rm -rf \
        /usr/share/apport \
        /usr/share/doc/* \
        /usr/share/gcc \
        /usr/share/gdb \
        /usr/share/vim/vim90/macros/maze/*
}

# For these packages, we will remove them only and not their dependencies.
function force_remove_packages() {
    echo "Force Removing Packages"

    cat "${FORCE_REMOVE_PACKAGES_PATH}" | xargs dpkg --remove --force-depends --force-remove-essential | true
    cat "${FORCE_REMOVE_PACKAGES_PATH}" | xargs dpkg --purge --force-depends --force-remove-essential | true
}

function unmount_live_disks() {
    sudo umount /usr/lib/live/mount/rootfs/filesystem.squashfs
    sudo umount /run/live/rootfs/filesystem.squashfs
}

# Patch some breaks that happen when we aggressively remove some software.
function fix_breaks() {
    # Replace a Perl script with a link.
    rm -f /usr/bin/x-terminal-emulator
    ln -s /usr/bin/xfce4-terminal /usr/bin/x-terminal-emulator
}

function main() {
    trap exit SIGINT
    set -e

    # Setup Users
    setup_users

    # Setup Desktop
    setup_desktop

    # Force Remove Packages
    force_remove_packages

    # Remove Files
    remove_files

    # Unmount Live Disks
    unmount_live_disks

    # Fix Breaks
    fix_breaks

    return 0
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
